# Generated by Django 5.2.8 on 2025-11-25 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_booking_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name="Nom de l'objet")),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Électronique'), ('DOCUMENTS', 'Documents'), ('LUGGAGE', 'Bagages'), ('CLOTHING', 'Vêtements'), ('ACCESSORIES', 'Accessoires'), ('JEWELRY', 'Bijoux'), ('BOOKS', 'Livres'), ('OTHER', 'Autre')], default='OTHER', max_length=20, verbose_name='Catégorie')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('color', models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marque')),
                ('location_found', models.CharField(max_length=200, verbose_name='Lieu de découverte')),
                ('date_found', models.DateTimeField(auto_now_add=True, verbose_name='Date de découverte')),
                ('status', models.CharField(choices=[('REPORTED', 'Signalé'), ('FOUND', 'Trouvé'), ('CLAIMED', 'Réclamé'), ('RETURNED', 'Restitué')], default='REPORTED', max_length=20, verbose_name='Statut')),
                ('reference_number', models.CharField(max_length=10, unique=True, verbose_name='Numéro de référence')),
                ('finder_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du découvreur')),
                ('finder_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du découvreur')),
                ('finder_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du découvreur')),
                ('claimer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du réclamant')),
                ('claimer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du réclamant')),
                ('claimer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone du réclamant')),
                ('claim_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de réclamation')),
                ('claim_details', models.TextField(blank=True, null=True, verbose_name='Détails de la réclamation')),
                ('returned_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de restitution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_objects', to='flights.flight', verbose_name='Vol associé')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_objects', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Objet perdu',
                'verbose_name_plural': 'Objets perdus',
                'ordering': ['-date_found'],
            },
        ),
    ]
